name: Email Step Test

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: 23f1001911@ds.study.iitm.ac.in
        run: echo "Hello, world!"
